const ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  POST_CREATED_BUT_NOT_FOUND: 'POST_CREATED_BUT_NOT_FOUND',
  POST_NOT_CREATED: 'POST_NOT_CREATED',
  POST_NOT_DELETED: 'POST_NOT_DELETED',
  POST_NOT_EDITED: 'POST_NOT_EDITED',
  COMMENT_NOT_CREATED: 'COMMENT_NOT_CREATED',
  REPLY_TO_COMMENT_FAILED: 'REPLY_TO_COMMENT_FAILED',
  SESSION_ERROR: 'SESSION_ERROR'
};

export default ERROR_CODES;
